spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}
  issuer: ${JWT_ISSUER}
cookie:
  refresh-expiration: ${COOKIE_REFRESH_EXPIRATION}
oauth2:
  kakao:
    tokenUri: https://kauth.kakao.com/oauth/token
    clientId: eda321e5223dd5d98990c2399f445cfd
    redirectUri: http://3.36.63.211/kakaologin
    getUserInfoUri: https://kapi.kakao.com/v2/user/me